# Generated by Django 2.2 on 2019-04-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_name', models.CharField(max_length=300, unique=True)),
                ('dis_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
