# Generated by Django 2.2 on 2019-04-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_name', models.CharField(max_length=300, unique=True)),
                ('dis_image', models.ImageField(blank=True, max_length=500, upload_to='pictures/%Y/%m/%d/')),
                ('dis_symptoms', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='diseases',
        ),
    ]
